check that ffmpeg is installed and stop if not
fixes https://github.com/mipops/dvrescue/issues/330

diff --git a/tools/dvpackager b/tools/dvpackager
--- a/tools/dvpackager
+++ b/tools/dvpackager
@@ -325,8 +325,11 @@ _report(){
 
 MATCH_FRAMES="d:frame[1]|"
 FFMPEG_PATH="$(which ffmpeg)"
-
-# verify that ffmpeg qualifies
+# verify that ffmpeg is installed and qualifies
+if [[ -z "${FFMPEG_PATH}" ]] ; then
+    echo "ffmpeg is not found. Please install ffmpeg. Version 4.4 or higher is recommended."
+    exit 1
+fi
 FFversion="$("${FFMPEG_PATH}" -version)"
 LAVFversion="$(echo "${FFversion}" | grep "libavformat" | head -n 1 | sed 's/[^0-9./]//g' | cut -d "/" -f 1)"
 LAVFversion_maj="$(echo "${LAVFversion}" | cut -d. -f1)"
