remove loop for multi-input
as many options only make sense in context of one file input

diff --git a/tools/dvpackager b/tools/dvpackager
--- a/tools/dvpackager
+++ b/tools/dvpackager
@@ -9,7 +9,7 @@ dvpackager
 Rewrap a DV stream. This script is part of the dvrescue project.
 
 Usage:
-dvpackager [options] file.dv [file2.dv file3.dv file4.dv]
+dvpackager [options] file.dv
 
 Options:
 
@@ -295,6 +295,13 @@ while getopts ":fsdto:e:l:L:SnvuhF:M:" opt ; do
     esac
 done
 shift "$((OPTIND-1))"
+DVFILE="${1}"
+shift
+if [[ "${UNPACKAGER}" != "Y" && "${@}" != "" ]] ; then
+    _report -w "Error: there are additional unused arguments (${*}). Please reference the DV file last."
+    _usage
+    exit 0
+fi
 MATCH_FRAMES="${MATCH_FRAMES%?}"
 OPT_INPUT=(-y)
 OPT_INPUT+=(-nostdin)
@@ -362,9 +369,7 @@ case "${EXT}" in
 esac
 OPT_OUTPUT+=(-f "$FORMAT")
 
-while [[ "${@}" != "" ]] ; do
     unset OUTPUTOPTS
-    DVFILE="${1}"
     BASENAME="$(basename "${DVFILE}")"
     if [[ -d "${OUTPUTDIR}" ]] ; then
         SIDECAR_DIR="${OUTPUTDIR}"
@@ -382,7 +387,6 @@ while [[ "${@}" != "" ]] ; do
     DVRESCUE_SCC="${SIDECAR_DIR}/${BASENAME}.dvrescue.scc"
     DVRESCUE_SCC_VTT="${SIDECAR_DIR}/${BASENAME}.dvrescue.scc.vtt"
     TOTAL_DVFRAMES_PACKAGED="0"
-    shift
     if [[ -f "${DVFILE}" ]] ; then
         if [[ "${REPORT_ONLY}" = "Y" ]] ; then
             echo -n "Analyzing ${BASENAME}"
@@ -401,8 +405,8 @@ while [[ "${@}" != "" ]] ; do
             dvrescue "${DVFILE}" "${OUTPUTOPTS[@]}" --xml-output "${DVRESCUE_XML_TEMP}"
             ERROR="$(xmlstarlet sel -N "d=https://mediaarea.net/dvrescue" -t -m "/d:dvrescue/d:media" -v "@error" -n "${DVRESCUE_XML_TEMP}")"
             if [[ -n "${ERROR}" ]] ; then
-                echo ". Error: ${BASENAME} (${ERROR}), skipping."
-                continue
+                echo ". Error: ${BASENAME} (${ERROR})."
+                exit 1
             else
                 # check if the sidecar directory is there
                 if [[ ! -d "${SIDECAR_DIR}" ]] ; then
@@ -587,4 +591,3 @@ while [[ "${@}" != "" ]] ; do
     else
         echo "${BASENAME} is not a file, skipping."
     fi
-done
