add a gif output option

diff --git a/tools/dvplay b/tools/dvplay
--- a/tools/dvplay
+++ b/tools/dvplay
@@ -2,11 +2,12 @@
 SCRIPTDIR="$(dirname $(which "${0}"))"
 
 OPTIND=1
-while getopts ":s:mx" OPT ; do
+while getopts ":s:mxg" OPT ; do
     case "${OPT}" in
         s) START_TIME="${OPTARG}";;
         m) MASK_ONLY="Y" ;;
         x) ERROR_REVIEW="Y" ;;
+        g) GIF_OUTPUT="Y" ;;
         *) echo "bad option -${OPTARG}" ; _usage ;;
         :) echo "Option -${OPTARG} requires an argument" ; exit 1 ;;
     esac
@@ -73,6 +74,30 @@ _make_dvrescue_xml(){
   fi
 }
 
+_maketemp(){
+    mktemp -q "/tmp/$(basename "${0}").XXXXXX"
+    if [ "${?}" -ne 0 ]; then
+        echo "${0}: Can't create temp file, exiting..."
+        _writeerrorlog "_maketemp" "was unable to create the temp file, so the script had to exit."
+        exit 1
+    fi
+}
+
+_mkdir2(){
+    local DIR2MAKE=""
+    while [ "${*}" != "" ] ; do
+        DIR2MAKE="${1}"
+        if [ ! -d "${DIR2MAKE}" ] ; then
+            mkdir -p "${DIR2MAKE}"
+            if [ "${?}" -ne 0 ]; then
+                _report -wt "${0}: Can't create directory at ${DIR2MAKE}"
+                exit 1
+            fi
+        fi
+        shift
+    done
+}
+
 while [[ "${@}" != "" ]] ; do
   DVFILE="${1}"
   shift
@@ -80,10 +105,11 @@ while [[ "${@}" != "" ]] ; do
   SIDECAR_DIR="${DVFILE}_dvrescue"
   DVRESCUE_XML="${SIDECAR_DIR}/${BASENAME}.dvrescue.xml"
 
-  if [[ "${ERROR_REVIEW}" = "Y" ]] ; then
+  if [[ "${ERROR_REVIEW}" = "Y" ]] || [[ "${GIF_OUTPUT}" = "Y" ]] ; then
     _make_dvrescue_xml
     echo "Making jpegs of errors within $(basename "${DVFILE}")..."
     TOTAL_FRAMES="$(xmlstarlet sel -N d="https://mediaarea.net/dvrescue" -t -m "d:dvrescue/d:media" -v "sum(d:frames/@count)" -n "${DVRESCUE_XML}")"
+    COUNTER=1
     xmlstarlet sel -N d="https://mediaarea.net/dvrescue" -t -m "d:dvrescue/d:media/d:frames/d:frame[d:sta]" -v @n -o "," -v @pts -o "," -v @tc -n "${DVRESCUE_XML}" | while read error_frame ; do
       N="$(echo "${error_frame}" | cut -d "," -f1)"
       PTS="$(echo "${error_frame}" | cut -d "," -f2)"
@@ -92,13 +118,25 @@ while [[ "${@}" != "" ]] ; do
       PTS_C="$(echo "${PTS}" | sed 's|:|-|g')"
       PTS_E="$(echo "${PTS}" | sed 's|:|\\:|g')"
       TC_E="$(echo "${TC}" | sed 's|:|\\:|g')"
-      JPG_OUTPUT="${SIDECAR_DIR}/${BASENAME}_${TC_FILENAME_SAFE}.jpg"
+      if [[ "${GIF_OUTPUT}" = "Y" ]] ; then
+        _mkdir2 "${SIDECAR_DIR}/dvrescue_tmp"
+        JPG_OUTPUT="${SIDECAR_DIR}/dvrescue_tmp/${BASENAME}_$(echo "$COUNTER" | awk '{ printf("%06i", $1) }').jpg"
+      else
+        JPG_OUTPUT="${SIDECAR_DIR}/${BASENAME}_${TC_FILENAME_SAFE}.jpg"
+      fi
       ffmpeg -ss "${PTS}" -i "${DVFILE}" -vframes:v 1 -c:v copy -f rawvideo - | \
       xxd -p -c 80 | \
       perl -pe "s|${FIND}|${FILL}|g" | \
       xxd -r -p | \
       ffmpeg -y -i - -vf "pad=w=iw:h=ih+24:x=0:y=24:color=gray,drawbox=t=fill:w=iw*(${N}/${TOTAL_FRAMES}):h=24:c=silver:x=0:y=0,drawtext=fontfile=${DEFAULTFONT}:y=4:x=4:text='PTS=${PTS_E} TC=${TC_E} Frame=${N}'" "${JPG_OUTPUT}"
+      ((COUNTER=COUNTER+1))
     done
+    if [[ "${GIF_OUTPUT}" = "Y" ]] ; then
+      GIF_PALETTE="$(_maketemp)"
+      ffmpeg -nostdin -f image2 -i "${SIDECAR_DIR}/dvrescue_tmp/${BASENAME}_%06d.jpg" -vf palettegen "${GIF_PALETTE}.png"
+      ffmpeg -nostdin -f image2 -i "${SIDECAR_DIR}/dvrescue_tmp/${BASENAME}_%06d.jpg" -i "${GIF_PALETTE}.png" -filter_complex paletteuse "${SIDECAR_DIR}/${BASENAME}_error.gif"
+      rm -r "${SIDECAR_DIR}/dvrescue_tmp" "${GIF_PALETTE}.png"
+    fi
   else
     _play_dv "${DVFILE}"
   fi
